FIO, AGE, CITY, PHONE, MAIL, EDUCATION, SKILLS, EXPERIENCE, PORTFOLIO, FULL_DAY, SALARY, SOURCE = range(12)
WEIGHTS = {
    AGE: 0,
    EDUCATION: 0,
    SKILLS: 0,
    EXPERIENCE: 0,
    FULL_DAY: 0,
    SALARY: 0,
}
